FROM node:12-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
ENV PROXY_API=$PROXY_API

RUN npm run build

CMD ["npm", "start" ]

# Expose port 
EXPOSE 3000