# Use a base image with Node.js
FROM node:18-alpine

# Set working directory inside the container
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Build React app
RUN npm run build

# Command to run your Express application
CMD ["npm", "start"]

# Expose port 3000
EXPOSE 3000

