# Use a base image with Node.js
FROM node:12-alpine

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Command to build your React application
RUN npm run build

# Command to serve the built React application
CMD ["npm", "start" ]

# Expose port (the port your React app will be served on)
EXPOSE 3000