version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000/
      - PROXY_API=http://localhoast:8000/
    networks:
      - breakroom_connection

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - breakroom_connection

networks:
  breakroom_connection:
    driver: bridge